### ISSUE TITLE
Error when creating multiple templates

### ISSUE THREAD

**Issue by thisisjamessmith** [rsanchez/eecli#23]
I get this when creating multiple templates with 

`eecli create:template something/index another-thing/index`

`PHP Fatal error:  Call to a member function addError() on a non-object in phar:///usr/local/Cellar/eecli/1.0.7/libexec/eecli.phar/src/CodeIgniter/Functions.php on line 78`

**Comment by thisisjamessmith** [comment]
Not sure if it's related or a separate issue, but I'm also unable to create fields with spaces in the Label like this. Tried with both double/single quotes and get an error about 'too many arguments'.

`eecli create:field:text "Job title" people_job 5`

**Comment by rsanchez** [comment]
Which version of EE are you using? And which shell (bash, zsh, etc.)? I can replicate the first one, but had no issue with the second. I'm thinking it might have something to do with your shell rather than with eecli itself.

**Comment by thisisjamessmith** [comment]
Using bash

**Comment by rsanchez** [comment]
Fix the original issue. The other...I'm not sure about. Maybe try escaping your spaces with a backslash instead of quotes?
