### ISSUE TITLE
Error with hasParameterOption compatibility

### ISSUE THREAD

**Issue by litzinger** [rsanchez/eecli#26]
I did a global install and added eecli to my path, then ran the command and got the following error.

eecli init
PHP Fatal error:  Declaration of eecli\Console\GlobalArgvInput::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in /Users/blitzing/.composer/vendor/eecli/eecli/src/Console/GlobalArgvInput.php on line 32

Fatal error: Declaration of eecli\Console\GlobalArgvInput::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in /Users/blitzing/.composer/vendor/eecli/eecli/src/Console/GlobalArgvInput.php on line 32

**Comment by rsanchez** [comment]
Thanks for the pull. I ended up fixing this another way. You should download 1.1.0
